services:
  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse_server
    restart: always
    env_file:
      - .env
    ports:
      - "${CLICKHOUSE_PORT}:8123"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
