version: '3'

services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - myDatabase:/var/lib/mysql

volumes:
  myDatabase:  
